import type Konva from "konva";
import { type Metadata } from "next";
import { Lato, Source_Code_Pro } from "next/font/google";
import { Toaster } from "react-hot-toast";
import { GoogleTagManager } from "@next/third-parties/google";
import "./globals.css";

import { Providers } from "./providers";

declare global {
  interface Window {
    Konva: typeof Konva;
  }
}

const lato = Lato({
  subsets: ["latin"],
  weight: ["400", "700", "900"],
  variable: "--lato-font",
});
const martianMono = Source_Code_Pro({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--code-font",
});

export const metadata: Metadata = {
  title: "Lace Anatomy",
  description: "Generated by Tx Pipe",
  icons: [{ rel: "icon", url: "/txpipe.png" }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${lato.variable} ${martianMono.variable}`}>
      {process.env.NODE_ENV === 'production' && process.env.NEXT_PUBLIC_GA_TRACKING_ID && (
        <GoogleTagManager gtmId={process.env.NEXT_PUBLIC_GA_TRACKING_ID} />
      )}
      <body>
        <Providers>
          <div className="m-auto flex w-full flex-col">{children}</div>
          <Toaster position="bottom-center" />
        </Providers>
      </body>
    </html>
  );
}
