/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface ShelleyPart {
  isScript: boolean
  hash?: string
  pointer?: string
}
export interface AddressDiagnostic {
  kind: string
  network?: string
  paymentPart?: ShelleyPart
  delegationPart?: ShelleyPart
  byronCbor?: string
}
export interface Output {
  error?: string
  bytes?: string
  address?: AddressDiagnostic
}
export interface Datum {
  hash: string
  bytes: string
  json: string
}
export interface OutputUtxo {
  txHash: string
  index: number
  bytes: string
  address: string
  lovelace: number
  datum?: Datum
  assets: Array<Assets>
  scriptRef?: string
}
export interface InputUtxo {
  txHash: string
  index: string
}
export interface Asset {
  assetName: string
  assetNameAscii?: string
  coint?: number
}
export interface Assets {
  policyId: string
  assetsPolicy: Array<Asset>
}
export interface MetadataItem {
  label: string
  jsonMetadata: Record<string, string>
}
export interface WithdrawalItem {
  rawAddress: string
  amount: string
}
export interface Certificates {
  json: string
}
export interface CborResponse {
  txHash: string
  fee?: string
  inputs: Array<InputUtxo>
  referenceInputs: Array<InputUtxo>
  outputs: Array<OutputUtxo>
  mints: Array<Assets>
  metadata: Array<MetadataItem>
  withdrawals: Array<WithdrawalItem>
  certificates: Array<Certificates>
  size: string
  scriptsSuccessful: boolean
  error: string
}
export function cborParse(raw: string): CborResponse
export function napiParseDatumInfo(raw: string): Datum | null
