/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface ShelleyPart {
  isScript: boolean
  hash?: string
  pointer?: string
}
export interface AddressDiagnostic {
  kind: string
  network?: string
  paymentPart?: ShelleyPart
  delegationPart?: ShelleyPart
  byronCbor?: string
}
export interface Output {
  error?: string
  bytes?: string
  address?: AddressDiagnostic
}
export interface Datum {
  hash: string
  bytes: string
  json: string
}
export interface OutputUtxo {
  txHash: string
  index: string
  datum?: Datum
  address: string
  assets: Array<Assets>
}
export interface InputUtxo {
  txHash: string
  index: string
}
export interface Assets {
  policyId: string
  assetName: string
  quantity: string
}
export interface CborResponse {
  txHash: string
  fee?: string
  inputs: Array<InputUtxo>
  referenceInputs: Array<InputUtxo>
  outputs: Array<OutputUtxo>
  mints: Array<Assets>
  scriptsSuccessful: boolean
  error: string
}
export declare function cborParse(raw: string): CborResponse
