/* auto-generated by NAPI-RS */
/* eslint-disable */
export interface AddressDiagnostic {
  kind: string
  network?: string
  paymentPart?: ShelleyPart
  delegationPart?: ShelleyPart
  byronCbor?: string
  bytes?: string
}

export interface Asset {
  assetName: string
  assetNameAscii?: string
  amount?: number
}

export interface Assets {
  policyId: string
  assetsPolicy: Array<Asset>
}

/**
 * Scripts attached to `auxiliary_data` (distinct from witness-set scripts).
 * In the current pallas version (1.0.0-alpha.3) only native scripts and
 * Plutus V1 scripts are accessible via the unified `alonzo::AuxiliaryData`
 * type; V2/V3 aux-data scripts require a future pallas update.
 */
export interface AuxiliaryDataScripts {
  nativeScripts: Array<NativeScript>
  plutusV1Scripts: Array<string>
}

export interface BlockCborResponse {
  header: BlockHeader
  transactions: Array<CborResponse>
  transactionsCount: number
}

export interface BlockHeader {
  era: string
  blockNumber?: number
  slot?: number
  hash: string
  previousHash?: string
  issuerVkey?: string
  vrfVkey?: string
  blockBodySize?: number
  blockBodyHash?: string
}

/**
 * A Byron-era bootstrap (signature) witness (witness_set key 2).
 * All fields are hex-encoded bytes.
 */
export interface BootstrapWitness {
  /** Hex-encoded Ed25519 extended public key (64 bytes) */
  publicKey: string
  /** Hex-encoded signature */
  signature: string
  /** Hex-encoded chain code (32 bytes) */
  chainCode: string
  /** Hex-encoded address attributes (network magic / derivation path) */
  attributes: string
}

export declare function cborParse(raw: string): SafeCborResponse

export declare function cborParseBlock(raw: string): SafeBlockCborResponse

export interface CborResponse {
  era: string
  txHash: string
  scriptsSuccessful: boolean
  fee?: number
  inputs: Array<Input>
  referenceInputs: Array<Input>
  outputs: Array<Utxo>
  mints: Array<Assets>
  validityStart?: number
  ttl?: number
  /** Hex-encoded auxiliary data hash (tx_body key 7) */
  auxiliaryDataHash?: string
  /** Hex-encoded script data hash (tx_body key 11) */
  scriptDataHash?: string
  /** Hex-encoded required signer keyhashes (tx_body key 14) */
  requiredSigners: Array<string>
  /** Network id: 0 = testnet, 1 = mainnet (tx_body key 15) */
  networkId?: number
  metadata: Array<Metadata>
  withdrawals: Array<Withdrawal>
  certificates: Array<Certificates>
  collateral: Collateral
  /** Conway governance voting procedures (tx_body key 19) */
  votingProcedures: Array<VotingProcedure>
  /** Conway governance proposal procedures (tx_body key 20) */
  proposalProcedures: Array<ProposalProcedure>
  /** Current treasury value in lovelace (tx_body key 21) */
  currentTreasuryValue?: number
  /** Donation to treasury in lovelace (tx_body key 22) */
  donation?: number
  witnesses: Witnesses
  /** Scripts embedded in auxiliary_data (distinct from witness-set scripts) */
  auxiliaryScripts: AuxiliaryDataScripts
  size: number
  cbor?: string
}

export interface Certificates {
  json: string
}

export interface Collateral {
  total?: number
  collateralReturn: Array<Input>
}

export interface Datum {
  hash: string
  bytes: string
  json: string
}

export declare function downloadBlock(nodeUrl: string, magic: number, slot: number, hash: string): Promise<Array<number>>

export interface ExUnits {
  mem: number
  steps: number
}

export interface Input {
  txHash: string
  index: number
}

export interface Metadata {
  label: string
  jsonMetadata: Record<string, string>
}

/**
 * A native script from the transaction witness set (key 1).
 * Serialised as canonical JSON matching the pallas `NativeScript` serde output.
 */
export interface NativeScript {
  json: string
}

export declare function parseAddress(raw: string): SafeAddressResponse

export declare function parseDatumInfo(raw: string): Datum | null

/**
 * One entry from the `proposal_procedures` set (tx_body key 20).
 * The governance action is serialised as JSON because it is a complex enum.
 */
export interface ProposalProcedure {
  deposit: number
  /** Hex-encoded reward account bytes */
  rewardAccount: string
  /** Serde-JSON of the `GovAction` enum */
  govActionJson: string
  anchorUrl: string
  anchorDataHash: string
}

export interface Redeemer {
  tag: string
  index: number
  dataJson: string
  exUnits: ExUnits
}

export interface SafeAddressResponse {
  error?: string
  address?: AddressDiagnostic
}

export interface SafeBlockCborResponse {
  cborRes?: BlockCborResponse
  error: string
}

export interface SafeCborResponse {
  cborRes?: CborResponse
  error: string
}

export interface ShelleyPart {
  isScript: boolean
  hash?: string
  pointer?: string
}

export interface Utxo {
  txHash: string
  index: number
  bytes: string
  address: string
  lovelace: number
  datum?: Datum
  assets: Array<Assets>
  scriptRef?: string
}

/**
 * One row from the `voting_procedures` map (tx_body key 19).
 * Complex sub-structures (voter type) are encoded in `voter_json`.
 */
export interface VotingProcedure {
  /** Serde-JSON of the `Voter` enum (ConstitutionalCommitteeKey/Script, DRepKey/Script, StakePoolKey) */
  voterJson: string
  govActionTxHash: string
  govActionIndex: number
  /** "No" | "Yes" | "Abstain" */
  vote: string
  anchorUrl?: string
  anchorDataHash?: string
}

export interface Withdrawal {
  rawAddress: string
  amount: number
}

export interface Witness {
  key: string
  hash: string
  signature: string
}

export interface Witnesses {
  vkeyWitnesses: Array<Witness>
  bootstrapWitnesses: Array<BootstrapWitness>
  nativeScripts: Array<NativeScript>
  redeemers: Array<Redeemer>
  plutusData: Array<Datum>
  plutusV1Scripts: Array<string>
  plutusV2Scripts: Array<string>
  plutusV3Scripts: Array<string>
}
