/* auto-generated by NAPI-RS */
/* eslint-disable */
export interface AddressDiagnostic {
  kind: string
  network?: string
  paymentPart?: ShelleyPart
  delegationPart?: ShelleyPart
  byronCbor?: string
  bytes?: string
}

export interface Anchor {
  url: string
  hash: string
}

export interface Asset {
  assetName: string
  assetNameAscii?: string
  amount?: number
}

export interface Assets {
  policyId: string
  assetsPolicy: Array<Asset>
}

export interface BlockCborResponse {
  header: BlockHeader
  transactions: Array<CborResponse>
  transactionsCount: number
}

export interface BlockHeader {
  era: string
  blockNumber?: number
  slot?: number
  hash: string
  previousHash?: string
  issuerVkey?: string
  vrfVkey?: string
  blockBodySize?: number
  blockBodyHash?: string
}

export declare function cborParse(raw: string): SafeCborResponse

export declare function cborParseBlock(raw: string): SafeBlockCborResponse

export interface CborResponse {
  era: string
  txHash: string
  scriptsSuccessful: boolean
  fee?: number
  inputs: Array<Input>
  referenceInputs: Array<Input>
  outputs: Array<Utxo>
  mints: Array<Assets>
  validityStart?: number
  ttl?: number
  metadata: Array<Metadata>
  withdrawals: Array<Withdrawal>
  certificates: Array<Certificate>
  collateral: Collateral
  witnesses: Witnesses
  size: number
  cbor?: string
}

export type Certificate =
  | { kind: 'NotApplicable' }
  | { kind: 'StakeRegistration', stakeCredential: Credential }
  | { kind: 'StakeDeregistration', stakeCredential: Credential }
  | { kind: 'StakeDelegation', stakeCredential: Credential, poolKeyhash: string }
  | { kind: 'PoolRegistration', poolParams: PoolParams }
  | { kind: 'PoolRetirement', poolKeyhash: string, epoch: number }
  | { kind: 'Reg', stakeCredential: Credential, coin: number }
  | { kind: 'UnReg', stakeCredential: Credential, coin: number }
  | { kind: 'VoteDeleg', stakeCredential: Credential, drep: DRep }
  | { kind: 'StakeVoteDeleg', stakeCredential: Credential, poolKeyhash: string, drep: DRep }
  | { kind: 'StakeRegDeleg', stakeCredential: Credential, poolKeyhash: string, coin: number }
  | { kind: 'VoteRegDeleg', stakeCredential: Credential, drep: DRep, coin: number }
  | { kind: 'StakeVoteRegDeleg', stakeCredential: Credential, poolKeyhash: string, drep: DRep, coin: number }
  | { kind: 'AuthCommitteeHot', committeeColdCredential: Credential, committeeHotCredential: Credential }
  | { kind: 'ResignCommitteeCold', committeeColdCredential: Credential, anchor?: Anchor }
  | { kind: 'RegDRepCert', drepCredential: Credential, coin: number, anchor?: Anchor }
  | { kind: 'UnRegDRepCert', drepCredential: Credential, coin: number }
  | { kind: 'UpdateDRepCert', drepCredential: Credential, anchor?: Anchor }
  | { kind: 'GenesisKeyDelegation', genesishash: string, genesisDelegateHash: string, vrfKeyhash: string }
  | { kind: 'MoveInstantaneousRewardsCert', source: 'Reserves' | 'Treasury', stakeCredentials?: Array<MirTarget>, otherAccountingPot?: number }

export interface Collateral {
  total?: number
  inputs: Array<Input>
  collateralReturn: Array<Utxo>
}

export interface Credential {
  credentialType: 'Key' | 'Script'
  hash: string
}

export interface Datum {
  hash: string
  bytes: string
  json: string
}

export declare function downloadBlock(nodeUrl: string, magic: number, slot: number, hash: string): Promise<Array<number>>

export interface DRep {
  drepType: 'Key' | 'Script' | 'Abstain' | 'NoConfidence'
  hash?: string
}

export interface ExUnits {
  mem: number
  steps: number
}

export interface Input {
  txHash: string
  index: number
}

export interface Metadata {
  label: string
  jsonMetadata: Record<string, string>
}

export interface MirTarget {
  credential: Credential
  amount: number
}

export declare function parseAddress(raw: string): SafeAddressResponse

export declare function parseDatumInfo(raw: string): Datum | null

export interface PoolParams {
  operator: string
  vrfKeyhash: string
  pledge: number
  cost: number
  marginNumerator: number
  marginDenominator: number
  rewardAccount: string
  poolOwners: Array<string>
  relays: Array<Relay>
  poolMetadataUrl?: string
  poolMetadataHash?: string
}

export interface Redeemer {
  tag: string
  index: number
  dataJson: string
  exUnits: ExUnits
}

export interface Relay {
  relayType: 'SingleHostAddr' | 'SingleHostName' | 'MultiHostName'
  port?: number
  ipv4?: string
  ipv6?: string
  dnsName?: string
}

export interface SafeAddressResponse {
  error?: string
  address?: AddressDiagnostic
}

export interface SafeBlockCborResponse {
  cborRes?: BlockCborResponse
  error: string
}

export interface SafeCborResponse {
  cborRes?: CborResponse
  error: string
}

export interface ShelleyPart {
  isScript: boolean
  hash?: string
  pointer?: string
}

export interface Utxo {
  txHash: string
  index: number
  bytes: string
  address: string
  lovelace: number
  datum?: Datum
  assets: Array<Assets>
  scriptRef?: string
}

export interface Withdrawal {
  rawAddress: string
  amount: number
}

export interface Witness {
  key: string
  hash: string
  signature: string
}

export interface Witnesses {
  vkeyWitnesses: Array<Witness>
  redeemers: Array<Redeemer>
  plutusData: Array<Datum>
  plutusV1Scripts: Array<string>
  plutusV2Scripts: Array<string>
  plutusV3Scripts: Array<string>
}
